### ISSUE TITLE
MRGT producess error without saying which file caused the problem

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#14]
Here is the proof:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/436bfdcb-fc52-4f34-a7e3-d633339ac05b)

The error was caused by the frontmatter having two items called `glossaryTerm`, and has been fixed in the meantime.

The bug here is that 

1. while the line and column numbers were provided, the filename was not. This bug might also exist in other tools, as it seems a rather generic one.
2. the MRGT crashes (rather than continuing with the next curated text file), which means that other, similar errors only get noticed when this error is fixed and you bump into the next.

**Comment by Ca5e** [comment]
You're correct! The error should not fall back all the way to the instruction, instead it should be recognized that something went wrong while loading a curated text. I've added a try/catch block so a similar error will now look like this, continuing after the error is shown. I've noted this issue so I can correct this in other tools as well if it exists. I still want to go over every possible error case in the near future.

![image](https://github.com/tno-terminology-design/tev2-tools/assets/6130478/e1b54208-3c7d-4eac-9da5-7a3ebee1a1fa)
