### ISSUE TITLE
HRGT leest geen bestanden (althans: lokaal niet)

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#18]
Toen ik met de hand een demo wilde geven van de TEv2 tools, liep alles als een zonnetje totdat ik bij de HRGT kwam.

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/c05b44cd-e903-4117-9cb7-571a7200e7e3)

Het screenshot hierboven laat zien dat
- de HRGT de bestanden `*gloss*.md` wil lezen
- de HRGT dat niet voor mekaar krijgt
- deze bestanden wel degelijk gewoon bestaan.

Het 'gekke' is dat 
- dit een dag of wat geleden nog wel werkte
- als de bestanden in de config-file staan gespecificeerd, het ook werkt.

De commit waarin je dit fixt mag wat mij betreft dit issue meteen ook afsluiten.

**Comment by Ca5e** [comment]
Heb je misschien de glossary al eens gegenegeerd (dus er staan geen hrgrefs meer in de documenten)? Ik kan deze op geen enkel systeem reproduceren. De melding om aan te geven dat alles goed verloopt, maar er gewoon niets gevonden is, komt nog.
