### ISSUE TITLE
Kunnen we HRG-sorteerissues generiek detecteren?

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#19]
Hier is een voorbeeld, die (dat komt uit de tab `Curated Terms Glossary` van de pagina `Glossary Generation Demo`, maar die is intussen ook verholpen):

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/9be95ca9-e2c0-4dd8-ad9f-222d0e077a46)

Het moge duidelijk zijn dat `Terminology pattern` niet tussen `Navpath` en `Property (of a Concept)` thuishoort.

De oorzaak van dit geval was dat de entry met `glossaryTerm: Terminology Pattern` ook `term: pattern-terminology` heeft, waar blijkbaar op wordt gesorteerd. Dat was fout: er had `term: terminology` moeten staan en dat heb ik inmiddels gefixt.

Toch geeft dit te denken. Ik vraag me af of, en zo ja hoe dit (op een generieke manier, d.w.z. die voor alle converters geldig zou zijn) gedetecteerd had kunnen worden. Ideeen?

**Comment by Ca5e** [comment]
De HRGT sorteert op dit moment geen entries, de volgende regel staat dan ook nog in de HRGT code te wachten.

```typescript
// TODO: sort MRG entries according to the glossaryTerm?
```

Dit betekent dat de volgorde inderdaad (soort van) gebaseerd is op `term`; gezien de MRGT hier wel op sorteert voordat het een output levert. Sorteren op glossaryTerm heb ik in eerste instantie niet gedaan omdat daar destijds wat waarden voor ontbraken.

Sorteren op basis van de eerst gevonden letter van een outputregel van de converter (en zo verder), klinkt best mooi, maar dit gaat mogelijk al weer richting een slimmigheidje anders dan harde functionaliteit. Mogelijk kan wel getest worden op deze situatie en kan zo een melding worden gegeven als deze situatie anders is dan hetgeen dat als output wordt gezien.
Een `sort` attribuut in een hrgref vind ik ook geen gekke gedachte. Het onderstaand voorbeeld, waar `sort` de waarde kan krijgen van een mogelijke eigenschap van een MRG entry, kan ik me dan voorstellen. De vraag is dan wel opnieuw wat we doen als iemand bijvoorbeeld niet overal een `glossaryTerm` invult.

```
{% hrg="" converter="" sort="glossaryTerm" %}
```

**Comment by RieksJ** [comment]
Ik vind je suggestie wel goed. Kunnen we dan van `sort` ook niet zoeiets maken als `sort="{{#if}}{{glossaryTerm}} ..."`, dus een soort handlebars expressie?

**Comment by Ca5e** [comment]
> Ik vind je suggestie wel goed. Kunnen we dan van `sort` ook niet zoeiets maken als `sort="{{#if}}{{glossaryTerm}} ..."`, dus een soort handlebars expressie?

Lijkt me erg handig. We maken nu een nieuwe converter aan met de waarde van `sort` en sorteren op basis van de uitkomst van de converter die wordt uitgevoerd op alle entries.

Een stukje code delen is misschien wel leuk, gezien het hergebruik en de functionaliteit erg interessant is.
```typescript
    // Sort entries according to the sort parameter in the MRGRef
    if (mrgref.sort != null) {
      log.info(`\tSorting entries using '${mrgref.sort}'`)
      const sorter = new Converter({ template: mrgref.sort })
      entries.sort((a, b) => sorter.convert(a, mrgref).localeCompare(sorter.convert(b, mrgref)))
    }
```

**Comment by RieksJ** [comment]
Specs: (binnenkort kun je [hier](https://tno-terminology-design.github.io/tev2-specifications/docs/spec-tools/hrgt#hrg-sorting) zien hoe ik graag had dat het werkte...
- `sort` optie gaat werken als optie `-sort` of `--sort`, en kan ook opgegeven worden in MRGRef als 
    - `sort="<template>"` i.e., a mustache/[handlebars](https://handlebarsjs.com/guide/#what-is-handlebars) template
    - `sort="<predeftype>"`, predefined type ( `default` ).

Specifiaties van de predefined types: 
- default: [@Ca5e : graag beschrijven hoe je dat doet. Mijn voorkeur is sorteren op `term` en bij dezelfde termen, vervolgens op `type`.]
- ... [@Ca5e : graag beschrijven hoe deze alternatieve predefined types dan werken]

**Comment by Ca5e** [comment]
The newest versions of the tools now reflect these additions.

**Comment by RieksJ** [comment]
Zou je de [TRRT documentatie](https://tno-terminology-design.github.io/tev2-specifications/docs/spec-tools/trrt) en de [HRGT documentatie](https://tno-terminology-design.github.io/tev2-specifications/docs/spec-tools/hrgt) hierover eens kunnen reviewen? Ik ben benieuwd naar het volgende

- [x] het is begrijpbaar
- [x] spullen staan op een logische manier bij elkaar
- [x] wat er staat komt overeen met hoe het is geimplementeerd (niet alleen voor de 'sorter', maar ook voor ander spul)
- [ ] ... (wellicht heb je zelf nog opmerkingen)
