### ISSUE TITLE
`TRRT --help` does not correctly specify all options

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#22]
The TRRT now has the possibility to use multiple converters, so there is not only the option `--con` , but also others such as `--con[1]`, `--con[2]`, etc. When the tool is called with the `--help` parameter, it should show texts that help users to use these options (and in particular, it should be clear whether the 'con-array' starts with index `0` or `1`.

Perhaps it might pay off to check the other tools regarding the texts they produce when called with the `--help` function.

**Comment by RieksJ** [comment]
Los hiervan moet de [TRRT documentatie](https://tno-terminology-design.github.io/tev2-specifications/docs/spec-tools/trrt) nog worden aangepast op het idee van meerdere converters. Zou je daar eens naar willen kijken en een update doen?

**Comment by RieksJ** [comment]
The 

- [x] TRRT help function does not say anything about the error converter.
- [x] HRGT help function has the same problem. When #29 is addressed, the help function should also mention that there is an array of converters (as with the TRRT)

**Comment by Ca5e** [comment]
New helper texts are added within the newest version of the tools: hrgt@1.0.4 and trrt@1.0.16.
