### ISSUE TITLE
TRRT - TermRef processing doesn't seem to work (in eSSIF-Lab repo)

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#23]
If you look at the ['Parties, Actors, Actions' section](https://essif-lab.github.io/framework/docs/essifLab-pattern-list#parties-actors-and-actions) of the eSSIF-Lab framework, you see the following:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/84ad3bbf-42e1-4630-b55e-f6532465ea06)

The source code of the first sentence of the **Parties, Actors, Action section** has TermRef `[Parties, Actors and Actions pattern](party-actor-action@)`. Since there is only one MRGEntry with `term: party-actor-action`, this TermRef is correctly converted.

The source code of the first sentence of the **Jurisdictions section** has TermRef `[Jurisdictions pattern](pattern:jurisdiction@)`, which is not resolved (if you hover over the link, you'll see that in the lower left corner of the browser screen). This also holds for the first sentence of the **Guardianships** section.

**Comment by Ca5e** [comment]
I believe this to be fixed now with TRRT v1.0.15

**Comment by RieksJ** [comment]
The first sentence in the **guardianships** section has a termref that doesn't get resolved properly. The termref specifically mentions `pattern:guardianship`, yet it resolves to `concept:guardianship`.

**Comment by Ca5e** [comment]
Found the issue (changed one variable)... The fix is in the utils repo, both MRGT and TRRT will have this issue until the next versions.

**Comment by RieksJ** [comment]
When I work locally, and generate the tools locally, (using TRRT vsn 1.0.15), I see that term-parts of term refs are not yet regularized. Here's some evidence

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/b623b9a8-e2a3-4cb8-b0b4-f4bdcef72d9d)

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/e4d19571-323b-4e57-b1a2-b1deb999eb39)

**Comment by Ca5e** [comment]
Fixed within TRRT v1.0.16. Within the HRGT and TRRT interpreters, predefined capturing groups weren't being regularized.
