### ISSUE TITLE
TRRT default interpreter (regex) seems to be incorrect

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#24]
If you look at the log of the TRRT in the tev2-specifications repo, you can see the following:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/7514c707-eb2c-4c95-b226-2e48b916bc45)

Note lines 195, 200, and 208 (and there are more), where it says **TypeError: Cannot read properties of undefined (reading 'regex')**

**Comment by Ca5e** [comment]
The error was caused by the use of `{{noRefs glossaryText}}` as the `hoverText` of an MRG. I'll update the TRRT and utils when I've spent some time on other open issues. For now a fix is available in tev2-tools.
