### ISSUE TITLE
TRRT messages do not list the correct line numbers

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#26]
Here is part of the [TRRT log](https://github.com/tno-terminology-design/tev2-specifications/actions/runs/7432027298/job/20223372497) of a recent build.

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/5fb4f945-d98c-4217-beb6-48184032d255)

It shows the termref `[default scope](@)`, which the TRRT correctly thinks is an error. However, this termref is not at line 169 as the error message suggests, but (currently) at line 256, which is quite different.

This issue calls for making sure that 
- logging logs the correct line number
- and does so for all tools (I imagine this could be a more pervasive problem)

**Comment by Ca5e** [comment]
Fixed by separating the original loaded file from the modified/output file in the TRRT and HRGT. The index of a termref in the original loaded file was used to report on the modified file, which caused issues because the output file is typically a different length after processing.

**Comment by RieksJ** [comment]
This is not fixed, evidence of which is provided in #30.

**Comment by RieksJ** [comment]
That seems to be fixed now - see https://github.com/tno-terminology-design/tev2-tools/issues/30#issuecomment-1907889184
