### ISSUE TITLE
MRGT does not correctly regularize formphrases

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#30]
When generating the Digital Passports website, the log says:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/1122291a-3623-4083-adb6-f829066cc101)

-----

Here is (part of) the curated text that has the term ref `[AC](@)`. Note that the formphrases are used here in the free format that we discussed would be allowed.

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/b2c10b77-62e7-4f55-a949-2ccf6a13e9c7)

-----

Here is the front matter of the curated text: 

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/b203c124-5251-4696-969c-81cb2f31722c)

-----

Here is (part of) the MRG file `mrg.dp.yaml`: 

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/cee942de-416e-467c-94e6-76534bae0fff)

-----

And here are my observations:

- [x] the line number that the TRRT (version 1.0.14) mentions where the term ref cannot be resolved, is still wrong (should be fixed), so I have reopened #26.
- [x] the glossary that the TRRT mentions it has used, has an entry for the term `active configuration`, which has an entry `AC`. This is not a [regularized text](https://tno-terminology-design.github.io/tev2-specifications/docs/terms/regularized-text) (which it should be), as it contains upper-case characters. This is a bug that should be fixed.
- [x] When fixing the MRGT, it may be useful to also regularize some other fields before putting them into the MRG entry, such as the 'term' field, and possibly one or two others. Let's discuss this first.

**Comment by Ca5e** [comment]
I'm not sure what would be causing the line number issue right now. I have just bumped the versions and published them to npm. That would be TRRT 1.0.15, MRGT 1.0.3, HRGT 1.0.2, MRG-Import 1.0.3. Could you try these @RieksJ?

**Comment by RieksJ** [comment]
line numbers seem fixed. regularisation remains
