### ISSUE TITLE
`synonymOf` processing is broken.

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#31]
In order to come to grips with the processing of synonyms, I've create the term `writer`, with an associated curated text as follows:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/d8c580f9-ec78-4714-89c8-c5fac7f0b4ec)

The idea is that this curated text will produce an MRG entry that is identical with that of `author`, except for

1. the fields that are in the header of the specified ctext (in this case: `term` and `formPhrases`), and
2. the fields that the MRGT adds on its own accord.

This isn't what is done: the MRGT creates the following MRG entry:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/b9187a85-c02b-4ba0-af3e-ff3e482c31d1)

**Comment by Ca5e** [comment]
I rewrote the synonymOf logic in the MRGT version 1.0.4, it looks like it works again if we look at the essif-lab/framework repo [workflow](https://github.com/essif-lab/framework/commit/95ae0e40c6ea1e418820bfb0d6c14d61ab7d2e28). Should be a lot more efficient now too.

**Comment by RieksJ** [comment]
I don't see that it works. 

- [x] The term '[writer](https://tno-terminology-design.github.io/tev2-specifications/docs/terms/writer)' (in the tev2-specs) describes what it should do, but that doesn't seem to work.
- [x] Also, [its HRG entry](https://tno-terminology-design.github.io/tev2-specifications/docs/tev2-glossary#writer) says that it is undefined (which it shouldn't be as a synonym).
