### ISSUE TITLE
HRGT (a) produces text where it should not, and (b) uses wrong logging syntax

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#34]
Here is a part of the log when generating the tev2-specifications stuff:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/70e59cf0-5412-463c-9c33-dfb5b83e76fb)

While it is correct that the concept 'action' should not result in a converted text, the log should write `... 'concept:action' ...` rather than `... 'action:concept' ...`. 

The stuff that is actually generated is this:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/c3782602-4955-4399-96e2-b932bba80545)

As you can see, rather than NOT generating texts, the name of the converter is used as the text (which is wrong).

So:
- [x] the log should mention `<termType>:<term>` (instead of the other way around), and
- [x] when a converter does not produce any text, it's good to log that, but it should NOT produce a text as its regular output.

**Comment by Ca5e** [comment]
I've changed the behaviour slightly. Now, when no expression is filled, the replacement text is not added.
The replacement text is correct in the sense that `markdown-abbr-table-row` doesn't yet exist as a default in the latest published version, and is thus assumed to be the template. Will publish the new version tomorrow.
