### ISSUE TITLE
Which handlebar variables can be used in converters?

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#4]
[Handlebars expression](https://handlebarsjs.com/guide/#what-is-handlebars) that are used in converters (termref converters as well as mrgref converters) are typically expected to be able to use `{{<variablename>}}`, where `<variablename>` is the name of a field in an MRG-entry. Examples are `{{glossaryText}}`, or `{{hoverText}}`, or `{{termtype}}`, etc.

I can see there is a merit in being able to use variables that exist in the MRG's [terminology section](https://tno-terminology-design.github.io/tev2-specifications/docs/spec-files/mrg#mrg-terminology) or its [scopes section](https://tno-terminology-design.github.io/tev2-specifications/docs/spec-files/mrg#mrg-scopes). 

Questions:
- does this make sense?
- can we do this already, and if so, how
    - if so: how (where is it documented)?
    - if not: should we specify it (turning this issue into a feature/enhancement request)?

**Comment by Ca5e** [comment]
Handlebars is currently only given the entry and termref information for the TRRT and the entry and mrgref information for the HRGT. Meaning we can't access the corresponding MRG information yet. If this were to be added, using `{{mrg.terminology.scopetag}}` for example, seems logical.
Although this could definitely be added, I'm not sure which fields would be useful for use in the TRRT or HRGT.

**Comment by RieksJ** [comment]
Seems as this is a plan. So there will be variables of the form `{{mrg.terminology.<fieldname>}}`, where `<fieldname>` identifies a field in the `terminology` section of the current MRG. The variables of this form will produce the value of that field.

Also, the MRGT needs to be checked to ensure the ENTIRE first section of the SAF will be copied into the `terminology`-section of the MRGs that are generated within the SAF's scope

**Comment by Ca5e** [comment]
The newest versions of the tools now reflect these changes.
