### ISSUE TITLE
Problems with the processing of the `rename` instruction in the MRGT

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#41]
When using the MRGT on the tev2-specifications repo the result is this:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/3f101294-1f53-40d8-aa6a-00aa71288afc)

When generating `mrg.tev2.documentation.yaml`, the first instruction selects the term `action` from the `essif-lab` scope.
Then, the subsequent `rename` instruction tells it to rename the term, modifying fields `id` and `term` to become `act`, and modifying the `formphrases` field to become `act{ss}`. 

However, when I check the resulting mrg-file, I cannot find an entry for the renamed thing.

Note that the following termselection instruction again imports `action` from essif-lab. This should not overwrite the (renamed) `act` entry, but seems to do so.

**Comment by Ca5e** [comment]
The check for duplicates, which determines if an entry overwrites another entry within a provisional MRG, currently happens according to the `termid` property of an entry. I believe this issue stems from that, because the rename action doesn't alter the `termid`. I suppose this could be remedied by re-triggering the `termid` creation after a rename of the `term` or `termType`.

**Comment by RieksJ** [comment]
yes, please!

**Comment by RieksJ** [comment]
@Ca5e : This is (still) not fixed. 

The SAF says this:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/3cb2fad6-d1f7-4d95-b145-b20bd4100f92)

The log I just generated says this:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/57c5e7d6-1bdd-4208-b1ca-2e7455b64a3e)

I didn't expect to see (line 61) that a term got overwritten. And if the `rename` instruction worked, then indeed the mrg-entry 'action' got overwritten.

**Comment by Ca5e** [comment]
I hadn't published the newest versions yet. I have just done so, the [rerun](https://github.com/tno-terminology-design/tev2-specifications/actions/runs/8589086110/job/23534747427) on tev2-specifications seems to have fixed this.
