### ISSUE TITLE
MRGT fails to build locally

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#44]
If I attempt to build the tools locally (using `npm run rebuild --workspaces`), here's what I get as output:

![image](https://github.com/tno-terminology-design/tev2-tools/assets/8522589/413d7cb9-0d8c-4731-a108-9e980cee47ad)

**Comment by Ca5e** [comment]
Could you retry please? I've removed some remnants of the refactoring I did yesterday.

**Comment by RieksJ** [comment]
That's what a "quick fix" literally means!
