### ISSUE TITLE
Config file documentation (and related texts) must be checked

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#5]
Having drafted the [config file documentation](https://tno-terminology-design.github.io/tev2-specifications/docs/spec-files/configuration-file), I realized that there are some oddities that need to be checked against the implementation.

These include, but may not be limited to the following:

- there are some arguments, such as `help` or `version`, that have not that much use from within configuration files. It must be clarified what they mean: do they ONLY provide help/version text (and not do anything else), or do they show such texts and continue with any further processing. This bears relevance on whether or not the `scopedir` argument is required.
- the `onNotExist` parameter can be seen as generic (what to do when something of importance is checked but doe not exist), or specific, e.g., in the MRGT, `onNotExist` says what happens in case ` vsntag` was specified, but not found in the SAF.
- parameters for the HRGT must be checked. For example, the `interpreter` is currently not used - there is a fixed MRGRef syntax. Do we want to keep that, or do we want to make that the 'basic' interpreter for HRGTs, and enable converters to be specified for HRGs in the config file?

@Ca5e, can you check this and comment on this issue and/or adjust documentation where needed?

**Comment by Ca5e** [comment]
> there are some arguments, such as help or version, that have not that much use from within configuration files.

The arguments `help` and `version` are automatically generated by the commander package which is used to handle the commands and arguments. I suppose I could overwrite this default behaviour somehow and actually implement these commands based on any requested functionality.

> This bears relevance on whether or not the scopedir argument is required.

I'm not sure what's meant by this.

> the onNotExist parameter can be seen as generic

I'll look into the scenarios where onNotExist would be useful as well.

> parameters for the HRGT must be checked.

I'd say we interpret the interpreter of the HRGT the same as the TRRT, where we have a default, but any regex or (`default`) could also be provided.
