### ISSUE TITLE
Symlink paths too long - checkout impossible

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#8]
@Ca5e : can you pls check to see what happened [here](https://github.com/tno-terminology-design/tev2-specifications/actions/runs/7085097890/job/19280685654)? 

It seems as if the symlinks for the altvsntag-mrg's are too long 
I had already been thinking about the symlinks, and whether or not that is a good idea.
Perhaps we could replace the symlinks with simple file, whose contents is just the name of the file that contains the actual mrg. This would need some coding to ensure that if you read such a file and produce a list of mrg-entries (or whatever the internal way of representing the contents of the file is) checks for this.

Pls let me know when this is fixed.

**Comment by Ca5e** [comment]
Looking into it. I am quite surprised to see that these symlinks still exists, we already discussed that we won't be using symlinks anymore. The [framework](https://github.com/essif-lab/framework/tree/master/docs/glossaries) repo doesn't, for instance.

**Comment by Ca5e** [comment]
Fixed by removing the MRG's pretending to be symlinks.
