### ISSUE TITLE
HRGT doesn't work when a non-default MRG is specified

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#9]
When I have the following in a MD file, and the file `mrg.tev2.terms.yaml` exists:

``` markdown

| Term | Definition |
| ---- | ---------- |
{% hrg="terms" converter="markdowntable" %}

```

I expect that this creates a HRG in markdowntable style. However, the HRGT says 

`INFO    Found MRG reference '{% hrg="terms" converter="markdowntable" %}' in file 'tev2-glossaries.md'` 

and 
- there is no error/warning message, and
- nothing is generated (the MRGref remains as is).

**Comment by Ca5e** [comment]
There should indeed be an error displayed here.
Unless there is a scope named terms, the behaviour of not generating seems correct. If we're referring to a vsntag named `terms`, the terminology identifier should be `:terms` according to the [specs](https://tno-terminology-design.github.io/tev2-specifications/docs/spec-syntax/terminology-identifier-syntax#syntax):
```
(empty string, null)
scopetag
scopetag:vsntag
:vsntag
```

**Comment by Ca5e** [comment]
Interpretation of the hrg field has been modified and an error has been added when the MRG can't be found based on the supplied value.
